// Schedule subcommand (P3, machine-product refactor): the declaration
// (kind + timezone + per-mode time/days) lives in machine config; unit
// files are generated by the driver and installed/verified against it.
import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import { makeFactory, runDriver } from "./helpers.mjs";
import {
  parseDaysSpec, formatDaysSpec, normalizeSchedule, validateDeclaration,
  declarationFromAnswers, generateUnits, generateSupervisorUnits,
  parseInstalled, compareInstalled, nextFire,
} from "../schedule.mjs";

// ---------- days spec ----------

test("parseDaysSpec accepts ranges, lists, and combinations", () => {
  assert.deepEqual(parseDaysSpec("Mon-Fri"), ["Mon", "Tue", "Wed", "Thu", "Fri"]);
  assert.deepEqual(parseDaysSpec("Mon-Sun"), ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]);
  assert.deepEqual(parseDaysSpec("Mon,Wed,Fri"), ["Mon", "Wed", "Fri"]);
  assert.deepEqual(parseDaysSpec("Mon-Wed,Sat"), ["Mon", "Tue", "Wed", "Sat"]);
  assert.deepEqual(parseDaysSpec("sat,sun"), ["Sat", "Sun"], "case-insensitive");
});

test("parseDaysSpec rejects garbage", () => {
  assert.throws(() => parseDaysSpec("Funday"));
  assert.throws(() => parseDaysSpec(""));
  assert.throws(() => parseDaysSpec("Fri-Mon"), /range/i, "wrapping ranges are not supported");
});

test("formatDaysSpec renders canonical ranges and lists", () => {
  assert.equal(formatDaysSpec(["Mon", "Tue", "Wed", "Thu", "Fri"]), "Mon-Fri");
  assert.equal(formatDaysSpec(["Mon", "Wed", "Fri"]), "Mon,Wed,Fri");
  assert.equal(formatDaysSpec(["Mon", "Tue", "Wed", "Sat"]), "Mon-Wed,Sat");
  assert.equal(formatDaysSpec(["Sat"]), "Sat");
});

// ---------- declaration shape ----------

test("normalizeSchedule accepts the legacy string form as kind-only", () => {
  assert.deepEqual(normalizeSchedule("systemd"), { kind: "systemd", timezone: null, modes: null });
  assert.equal(normalizeSchedule(undefined), null);
  assert.equal(normalizeSchedule(null), null);
});

test("normalizeSchedule passes through the block form", () => {
  const d = normalizeSchedule({
    kind: "systemd", timezone: "Europe/Lisbon",
    modes: { dev: { time: "09:00", days: "Mon-Fri" } },
  });
  assert.equal(d.kind, "systemd");
  assert.equal(d.timezone, "Europe/Lisbon");
  assert.deepEqual(d.modes.dev, { time: "09:00", days: "Mon-Fri" });
});

test("validateDeclaration flags bad kind, time, days, timezone, and mode names", () => {
  assert.deepEqual(validateDeclaration({ kind: "manual", timezone: null, modes: null }), []);
  const problems = validateDeclaration({
    kind: "quartz", timezone: "Mars/Olympus",
    modes: { dev: { time: "25:99", days: "Fri-Mon" }, lunch: { time: "12:00", days: "Mon-Fri" } },
  });
  assert.ok(problems.some((p) => /kind/i.test(p)), `kind: ${problems}`);
  assert.ok(problems.some((p) => /timezone/i.test(p)), `timezone: ${problems}`);
  assert.ok(problems.some((p) => /25:99/.test(p)), `time: ${problems}`);
  assert.ok(problems.some((p) => /Fri-Mon/.test(p)), `days: ${problems}`);
  assert.ok(problems.some((p) => /lunch/.test(p)), `mode: ${problems}`);
});

test("declarationFromAnswers builds the block init writes into machine config", () => {
  const a = { schedule: "systemd", triageTime: "08:30", devTime: "09:00", reportTime: "13:30", workDays: "Mon-Fri" };
  assert.deepEqual(declarationFromAnswers(a), {
    kind: "systemd",
    modes: {
      triage: { time: "08:30", days: "Mon-Fri" },
      dev: { time: "09:00", days: "Mon-Fri" },
      report: { time: "13:30", days: "Mon-Fri" },
    },
  });
  assert.deepEqual(declarationFromAnswers({ schedule: "manual" }), { kind: "manual" });
});

// ---------- generation (golden) ----------

const CTX = {
  project: "/srv/app",
  projectName: "app",
  stateDir: "/home/u/.factory/projects/app-abcd1234",
  runtimeDriver: "/home/u/.factory/runtime/factory/driver/factory.mjs",
  nodeBin: "/usr/bin/node",
  windowHours: 4,
  pathLine: "/home/u/.local/bin:/usr/bin:/bin",
};

const DECL = {
  kind: "systemd",
  timezone: "Europe/Lisbon",
  modes: {
    triage: { time: "08:30", days: "Mon-Fri" },
    dev: { time: "09:00", days: "Mon-Sun" },
    report: { time: "13:30", days: "Mon-Fri" },
  },
};

test("generateUnits(systemd): one service template + one timer per mode", () => {
  const { files } = generateUnits({ ...DECL }, CTX);
  const names = Object.keys(files).sort();
  assert.deepEqual(names, ["app-dev.timer", "app-factory@.service", "app-report.timer", "app-triage.timer"]);

  const svc = files["app-factory@.service"];
  assert.match(svc, /^ExecStart=\/usr\/bin\/node \/home\/u\/\.factory\/runtime\/factory\/driver\/factory\.mjs %i --project \/srv\/app --scheduled$/m);
  assert.match(svc, /^Environment=PATH=\/home\/u\/\.local\/bin:\/usr\/bin:\/bin$/m);
  assert.match(svc, /^WorkingDirectory=\/srv\/app$/m);
  assert.match(svc, /^OnFailure=factory-onfailure@%n\.service$/m);
  assert.match(svc, /^TimeoutStartSec=8h$/m);

  const dev = files["app-dev.timer"];
  assert.match(dev, /^OnCalendar=Mon\.\.Sun 09:00 Europe\/Lisbon$/m, "per-mode days + timezone suffix");
  assert.match(dev, /^Unit=app-factory@dev\.service$/m);
  assert.match(dev, /^Persistent=false$/m);
  assert.match(files["app-triage.timer"], /^OnCalendar=Mon\.\.Fri 08:30 Europe\/Lisbon$/m);
});

test("generateUnits(systemd): no timezone declared means no OnCalendar suffix", () => {
  const { files } = generateUnits({ ...DECL, timezone: null }, CTX);
  assert.match(files["app-dev.timer"], /^OnCalendar=Mon\.\.Sun 09:00$/m);
});

test("generateUnits(cron): one managed block, CRON_TZ only when declared", () => {
  const { files } = generateUnits({ ...DECL, kind: "cron" }, CTX);
  const block = files["crontab-block"];
  assert.match(block, /^# BEGIN factory \/srv\/app /m);
  assert.match(block, /^# END factory \/srv\/app$/m);
  assert.match(block, /^CRON_TZ=Europe\/Lisbon$/m);
  assert.match(block, /^PATH=\/home\/u\/\.local\/bin:\/usr\/bin:\/bin$/m);
  assert.match(block, /^30 8 \* \* 1-5 \/usr\/bin\/node \/home\/u\/\.factory\/runtime\/factory\/driver\/factory\.mjs triage --project \/srv\/app --scheduled >> \/home\/u\/\.factory\/projects\/app-abcd1234\/log\/cron\.out 2>&1$/m);
  assert.match(block, /^0 9 \* \* \* .+ dev --project/m, "Mon-Sun renders as * for cron");

  const noTz = generateUnits({ ...DECL, kind: "cron", timezone: null }, CTX).files["crontab-block"];
  assert.doesNotMatch(noTz, /CRON_TZ/);
});

test("generateUnits(launchd): one plist per mode, weekday dicts, system-TZ note", () => {
  const { files, notes } = generateUnits({ ...DECL, kind: "launchd" }, CTX);
  const names = Object.keys(files).sort();
  assert.deepEqual(names, [
    "com.factory.app.dev.plist", "com.factory.app.report.plist", "com.factory.app.triage.plist",
  ]);
  const triage = files["com.factory.app.triage.plist"];
  assert.match(triage, /<string>\/home\/u\/\.factory\/runtime\/factory\/driver\/factory\.mjs<\/string><string>triage<\/string>/);
  assert.match(triage, /<string>--scheduled<\/string>/);
  // Mon-Fri = launchd weekdays 1..5, at 08:30
  for (const wd of [1, 2, 3, 4, 5]) {
    assert.match(triage, new RegExp(`<key>Weekday</key><integer>${wd}</integer><key>Hour</key><integer>8</integer><key>Minute</key><integer>30</integer>`));
  }
  assert.match(triage, new RegExp("StandardOutPath</key><string>/home/u/\\.factory/projects/app-abcd1234/log/launchd-triage\\.out"), "logs go machine-side");
  // launchd cannot express a timezone — declared TZ must surface as a note
  assert.ok(notes.some((n) => /timezone|system/i.test(n)), `notes: ${notes}`);
});

// ---------- adopt: parse installed artifacts back into a declaration ----------

test("parseInstalled(systemd) recovers times, days, and timezone from unit files", () => {
  const artifacts = [
    { name: "app-factory@.service", text: "[Unit]\nOnFailure=factory-onfailure@%n.service\n\n[Service]\nEnvironment=PATH=/usr/bin:/bin\nExecStart=/usr/bin/node /home/u/.factory/runtime/factory/driver/factory.mjs %i --project /srv/app --scheduled\n" },
    { name: "app-triage.timer", text: "[Timer]\nOnCalendar=Mon..Fri 08:30 Europe/Lisbon\nPersistent=false\nUnit=app-factory@triage.service\n" },
    { name: "app-dev.timer", text: "[Timer]\nOnCalendar=Mon..Sun 09:00:00 Europe/Lisbon\nUnit=app-factory@dev.service\n" },
  ];
  const { decl, problems } = parseInstalled("systemd", artifacts, CTX);
  assert.deepEqual(problems, []);
  assert.equal(decl.kind, "systemd");
  assert.equal(decl.timezone, "Europe/Lisbon");
  assert.deepEqual(decl.modes.triage, { time: "08:30", days: "Mon-Fri" });
  assert.deepEqual(decl.modes.dev, { time: "09:00", days: "Mon-Sun" }, "seconds are normalized away");
  assert.equal(decl.modes.report, undefined, "only installed modes are declared");
});

test("parseInstalled(systemd) reports an unparseable OnCalendar instead of guessing", () => {
  const artifacts = [
    { name: "app-dev.timer", text: "[Timer]\nOnCalendar=*-*-01 04:00\nUnit=app-factory@dev.service\n" },
  ];
  const { problems } = parseInstalled("systemd", artifacts, CTX);
  assert.ok(problems.some((p) => p.includes("app-dev.timer") && p.includes("*-*-01 04:00")), `problems: ${problems}`);
});

test("parseInstalled(launchd) recovers weekdays and time from a plist", () => {
  const cal = [1, 2, 3, 4, 5].map((d) =>
    `<dict><key>Weekday</key><integer>${d}</integer><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict>`).join("\n");
  const artifacts = [{
    name: "com.factory.app.dev.plist",
    text: `<plist><dict><key>Label</key><string>com.factory.app.dev</string>
<key>ProgramArguments</key><array><string>/usr/bin/node</string><string>/home/u/.factory/runtime/factory/driver/factory.mjs</string><string>dev</string><string>--project</string><string>/srv/app</string><string>--scheduled</string></array>
<key>StartCalendarInterval</key><array>${cal}</array></dict></plist>`,
  }];
  const { decl, problems } = parseInstalled("launchd", artifacts, CTX);
  assert.deepEqual(problems, []);
  assert.deepEqual(decl.modes.dev, { time: "09:00", days: "Mon-Fri" });
});

test("parseInstalled(cron) recovers entries and CRON_TZ from the crontab text", () => {
  const text = [
    "PATH=/usr/bin:/bin",
    "CRON_TZ=Europe/Lisbon",
    "30 8 * * 1-5 /usr/bin/node /home/u/.factory/runtime/factory/driver/factory.mjs triage --project /srv/app --scheduled >> /x/cron.out 2>&1",
    "0 9 * * * /usr/bin/node /home/u/.factory/runtime/factory/driver/factory.mjs dev --project /srv/app --scheduled",
    "5 5 * * * /usr/bin/backup --project /srv/app-two",
  ].join("\n");
  const { decl, problems } = parseInstalled("cron", [{ name: "crontab", text }], CTX);
  assert.deepEqual(problems, []);
  assert.equal(decl.timezone, "Europe/Lisbon");
  assert.deepEqual(decl.modes.triage, { time: "08:30", days: "Mon-Fri" });
  assert.deepEqual(decl.modes.dev, { time: "09:00", days: "Mon-Sun" });
  assert.equal(decl.modes.report, undefined);
});

// ---------- semantic compare (doctor 12c) ----------

test("compareInstalled is clean when installed units match the declaration", () => {
  const { files } = generateUnits(DECL, CTX);
  const artifacts = Object.entries(files).map(([name, text]) => ({ name, text }));
  assert.deepEqual(compareInstalled(DECL, artifacts, CTX), []);
});

test("compareInstalled flags time drift, missing modes, extra modes, and a wrong exec line", () => {
  const { files } = generateUnits(DECL, CTX);
  // drift: dev timer fires at 10:00 instead of the declared 09:00
  const drifted = files["app-dev.timer"].replace("09:00", "10:00");
  const artifacts = [
    { name: "app-factory@.service", text: files["app-factory@.service"].replace("--scheduled", "") },
    { name: "app-dev.timer", text: drifted },
    // report + triage timers missing entirely
  ];
  const mismatches = compareInstalled(DECL, artifacts, CTX);
  assert.ok(mismatches.some((m) => /dev/.test(m) && /09:00/.test(m) && /10:00/.test(m)), `time drift: ${mismatches}`);
  assert.ok(mismatches.some((m) => /triage/.test(m) && /missing|not installed/i.test(m)), `missing: ${mismatches}`);
  assert.ok(mismatches.some((m) => /--scheduled/.test(m)), `exec: ${mismatches}`);
});

test("compareInstalled flags an installed mode the declaration does not have", () => {
  const { files } = generateUnits(DECL, CTX);
  const artifacts = Object.entries(files).map(([name, text]) => ({ name, text }));
  const decl = { ...DECL, modes: { dev: DECL.modes.dev } }; // only dev declared
  const mismatches = compareInstalled(decl, artifacts, CTX);
  assert.ok(mismatches.some((m) => /triage|report/.test(m) && /not declared|undeclared/i.test(m)), `${mismatches}`);
});

// ---------- supervisor unit generation (PR-D) ----------
// Machine-level daemon unit: one per machine, no project, kept alive by the
// OS (systemd Restart=always / launchd KeepAlive) — the fix for "the
// relauncher died silently".

const SUP_CTX = {
  runtimeSupervisor: "/home/u/.factory/runtime/factory/driver/supervisor.mjs",
  nodeBin: "/usr/bin/node",
  pathLine: "/home/u/.local/bin:/usr/bin:/bin",
  logDir: "/home/u/.factory/supervisor",
};

test("generateSupervisorUnits(systemd): one always-restarting service execing the runtime supervisor", () => {
  const { files } = generateSupervisorUnits("systemd", SUP_CTX);
  assert.deepEqual(Object.keys(files), ["factory-supervisor.service"]);
  const svc = files["factory-supervisor.service"];
  assert.match(svc, /^Restart=always$/m);
  assert.match(svc, /^ExecStart=\/usr\/bin\/node \/home\/u\/\.factory\/runtime\/factory\/driver\/supervisor\.mjs$/m);
  assert.match(svc, /^Environment=PATH=\/home\/u\/\.local\/bin:\/usr\/bin:\/bin$/m);
  assert.match(svc, /^OnFailure=factory-onfailure@%n\.service$/m);
  // Without an explicit start limit, Restart=always + RestartSec=10 never
  // trips systemd's default 10s burst window and OnFailure never fires.
  assert.match(svc, /^StartLimitIntervalSec=600$/m);
  assert.match(svc, /^StartLimitBurst=5$/m);
  assert.match(svc, /^WantedBy=default\.target$/m);
});

test("generateSupervisorUnits(launchd): a KeepAlive plist execing the runtime supervisor", () => {
  const { files } = generateSupervisorUnits("launchd", SUP_CTX);
  assert.deepEqual(Object.keys(files), ["com.factory.supervisor.plist"]);
  const plist = files["com.factory.supervisor.plist"];
  assert.match(plist, /<key>KeepAlive<\/key>\s*<true\/>/);
  assert.match(plist, /<key>RunAtLoad<\/key>\s*<true\/>/);
  assert.match(plist, /<string>\/usr\/bin\/node<\/string>\s*<string>\/home\/u\/\.factory\/runtime\/factory\/driver\/supervisor\.mjs<\/string>/);
  assert.match(plist, /<key>PATH<\/key><string>\/home\/u\/\.local\/bin:\/usr\/bin:\/bin<\/string>/);
  assert.match(plist, /<key>Label<\/key><string>com\.factory\.supervisor<\/string>/);
});

test("generateSupervisorUnits: kinds without a keep-alive manager produce no files, only a note", () => {
  for (const kind of ["cron", "schtasks", "manual"]) {
    const { files, notes } = generateSupervisorUnits(kind, SUP_CTX);
    assert.deepEqual(files, {}, kind);
    assert.ok(notes.some((n) => n.includes(kind)), `${kind}: ${notes}`);
  }
});

// ---------- CLI: declare / status ----------

const readConfig = (world) => JSON.parse(fs.readFileSync(path.join(world.stateDir, "config.json"), "utf8"));

test("schedule --declare writes the block into machine config and touches nothing else", (t) => {
  const world = makeFactory(t);
  const before = readConfig(world);

  const r = runDriver(world, "schedule", ["--declare", "--kind", "systemd", "--timezone", "Europe/Lisbon",
    "--days", "Mon-Fri", "--triage", "08:30", "--dev", "09:00", "--report", "13:30", "--dev-days", "Mon-Sun"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  const after = readConfig(world);
  assert.deepEqual(after.schedule, {
    kind: "systemd", timezone: "Europe/Lisbon",
    modes: {
      triage: { time: "08:30", days: "Mon-Fri" },
      dev: { time: "09:00", days: "Mon-Sun" },
      report: { time: "13:30", days: "Mon-Fri" },
    },
  });
  assert.equal(after.baseBranch, before.baseBranch, "other config keys survive");
  assert.equal(after.enabled, before.enabled);
});

test("schedule --declare refuses invalid input and leaves config untouched", (t) => {
  const world = makeFactory(t);
  const before = JSON.stringify(readConfig(world));

  const r = runDriver(world, "schedule", ["--declare", "--kind", "systemd", "--dev", "25:99"]);

  assert.equal(r.code, 1, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stderr, /25:99/);
  assert.equal(JSON.stringify(readConfig(world)), before);
});

test("schedule --declare --kind manual writes a bare manual declaration", (t) => {
  const world = makeFactory(t);
  const r = runDriver(world, "schedule", ["--declare", "--kind", "manual"]);
  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.deepEqual(readConfig(world).schedule, { kind: "manual" });
});

test("schedule --declare is interactive when given no answers (piped stdin)", (t) => {
  const world = makeFactory(t);
  // kind, timezone (empty = system), days, triage, dev, report
  const input = "systemd\n\nMon-Fri\n08:30\n09:00\n13:30\n";

  const r = runDriver(world, "schedule", ["--declare"], { input });

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  const s = readConfig(world).schedule;
  assert.equal(s.kind, "systemd");
  assert.equal(s.timezone, undefined, "empty timezone answer means machine TZ (key omitted)");
  assert.deepEqual(s.modes.dev, { time: "09:00", days: "Mon-Fri" });
});

test("schedule with no action flag prints status; legacy string config reads as kind-only", (t) => {
  const world = makeFactory(t); // fixture config: schedule: "manual"
  const r = runDriver(world, "schedule");
  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stdout, /manual/);
  assert.match(r.stdout, /no.*(times|modes) declared|kind only/i);
});

// ---------- CLI: install / uninstall (stubbed tools, fake HOME) ----------

const stubTool = (world, name, script) => {
  const p = path.join(world.root, "bin", name);
  fs.writeFileSync(p, script);
  fs.chmodSync(p, 0o755);
};
const stubSystemctl = (world) => {
  const logFile = path.join(world.root, "systemctl.log");
  stubTool(world, "systemctl", `#!/bin/sh\necho "$@" >> "${logFile}"\nexit 0\n`);
  return logFile;
};
const stubLaunchctl = (world) => {
  const logFile = path.join(world.root, "launchctl.log");
  stubTool(world, "launchctl", `#!/bin/sh\necho "$@" >> "${logFile}"\nexit 0\n`);
  return logFile;
};
const stubCrontab = (world) => {
  const file = path.join(world.root, "crontab.txt");
  stubTool(world, "crontab", `#!/bin/sh
if [ "$1" = "-l" ]; then [ -f "${file}" ] && cat "${file}" || exit 1; exit 0; fi
cat > "${file}"
`);
  return file;
};

const SYSTEMD_BLOCK = {
  kind: "systemd",
  modes: {
    triage: { time: "08:30", days: "Mon-Fri" },
    dev: { time: "09:00", days: "Mon-Fri" },
    report: { time: "13:30", days: "Mon-Fri" },
  },
};
const unitDir = (world) => path.join(world.home, ".config", "systemd", "user");

test("schedule --install (systemd) writes units, reloads, and enables the timers", (t) => {
  const world = makeFactory(t, { config: { schedule: SYSTEMD_BLOCK } });
  const ctl = stubSystemctl(world);

  const r = runDriver(world, "schedule", ["--install", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  for (const f of ["project-factory@.service", "project-triage.timer", "project-dev.timer", "project-report.timer"]) {
    assert.ok(fs.existsSync(path.join(unitDir(world), f)), `missing ${f}`);
  }
  assert.ok(fs.existsSync(path.join(unitDir(world), "factory-onfailure@.service")), "onfailure companion installed");
  const svc = fs.readFileSync(path.join(unitDir(world), "project-factory@.service"), "utf8");
  assert.match(svc, new RegExp(path.join(world.home, ".factory", "runtime", "factory", "driver", "factory.mjs").replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), "exec points at the machine runtime");
  const calls = fs.readFileSync(ctl, "utf8");
  assert.match(calls, /daemon-reload/);
  assert.match(calls, /enable --now .*project-dev\.timer/);
});

test("schedule --install is idempotent: a second run reports up to date and re-runs nothing", (t) => {
  const world = makeFactory(t, { config: { schedule: SYSTEMD_BLOCK } });
  const ctl = stubSystemctl(world);
  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0);
  const callsAfterFirst = fs.readFileSync(ctl, "utf8");

  const r = runDriver(world, "schedule", ["--install", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stdout, /up to date/i);
  assert.equal(fs.readFileSync(ctl, "utf8"), callsAfterFirst, "no systemctl calls on a no-op install");
});

test("schedule --install shows the diff and aborts without confirmation", (t) => {
  const world = makeFactory(t, { config: { schedule: SYSTEMD_BLOCK } });
  stubSystemctl(world);

  const r = runDriver(world, "schedule", ["--install"], { input: "n\n" });

  assert.equal(r.code, 1, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stdout, /project-dev\.timer/, "diff names the files it would write");
  assert.equal(fs.existsSync(path.join(unitDir(world), "project-dev.timer")), false, "nothing written on abort");
});

test("schedule --install refuses a kind-only declaration (no times) with a pointer", (t) => {
  const world = makeFactory(t, { config: { schedule: "systemd" } });
  stubSystemctl(world);
  const r = runDriver(world, "schedule", ["--install", "--yes"]);
  assert.equal(r.code, 1);
  assert.match(r.stderr, /--declare|--adopt/);
});

test("schedule --install on a manual declaration is a no-op", (t) => {
  const world = makeFactory(t, { config: { schedule: { kind: "manual" } } });
  const r = runDriver(world, "schedule", ["--install", "--yes"]);
  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stdout, /manual|nothing to install/i);
});

test("schedule --install (cron) maintains one managed block and preserves foreign lines", (t) => {
  const world = makeFactory(t, {
    config: { schedule: { ...SYSTEMD_BLOCK, kind: "cron", timezone: "Europe/Lisbon" } },
  });
  const cronFile = stubCrontab(world);
  fs.writeFileSync(cronFile, "5 5 * * * /usr/bin/backup\n");

  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0);
  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0, "reinstall must be idempotent");

  const cron = fs.readFileSync(cronFile, "utf8");
  assert.match(cron, /^5 5 \* \* \* \/usr\/bin\/backup$/m, "foreign line survives");
  assert.equal(cron.match(/# BEGIN factory /g).length, 1, "exactly one managed block");
  assert.match(cron, /CRON_TZ=Europe\/Lisbon/);
  assert.match(cron, /dev --project .* --scheduled/);
});

test("schedule --install (launchd) writes plists and reloads them", (t) => {
  const world = makeFactory(t, { config: { schedule: { ...SYSTEMD_BLOCK, kind: "launchd" } } });
  const ctl = stubLaunchctl(world);

  const r = runDriver(world, "schedule", ["--install", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  const la = path.join(world.home, "Library", "LaunchAgents");
  for (const m of ["triage", "dev", "report"]) {
    assert.ok(fs.existsSync(path.join(la, `com.factory.project.${m}.plist`)), `missing ${m} plist`);
  }
  assert.match(fs.readFileSync(ctl, "utf8"), /load .*com\.factory\.project\.dev\.plist/);
});

test("schedule --uninstall (systemd) disables timers and removes the unit files", (t) => {
  const world = makeFactory(t, { config: { schedule: SYSTEMD_BLOCK } });
  const ctl = stubSystemctl(world);
  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0);

  const r = runDriver(world, "schedule", ["--uninstall", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.equal(fs.existsSync(path.join(unitDir(world), "project-dev.timer")), false);
  assert.equal(fs.existsSync(path.join(unitDir(world), "project-factory@.service")), false);
  assert.match(fs.readFileSync(ctl, "utf8"), /disable --now .*project-dev\.timer/);
});

test("schedule --uninstall (cron) removes only this project's managed block", (t) => {
  const world = makeFactory(t, {
    config: { schedule: { ...SYSTEMD_BLOCK, kind: "cron" } },
  });
  const cronFile = stubCrontab(world);
  fs.writeFileSync(cronFile, "5 5 * * * /usr/bin/backup\n");
  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0);

  const r = runDriver(world, "schedule", ["--uninstall", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  const cron = fs.readFileSync(cronFile, "utf8");
  assert.match(cron, /backup/, "foreign line survives");
  assert.doesNotMatch(cron, /BEGIN factory|--scheduled/);
});

// ---------- CLI: adopt ----------

test("schedule --adopt parses installed systemd units into the machine-config declaration", (t) => {
  const world = makeFactory(t); // config still says schedule: "manual"
  const ud = unitDir(world);
  fs.mkdirSync(ud, { recursive: true });
  fs.writeFileSync(path.join(ud, "project-factory@.service"),
    `[Service]\nEnvironment=PATH=/usr/bin:/bin\nExecStart=/usr/bin/node ${path.join(world.home, ".factory", "runtime", "factory", "driver", "factory.mjs")} %i --project ${world.project} --scheduled\n`);
  fs.writeFileSync(path.join(ud, "project-dev.timer"),
    "[Timer]\nOnCalendar=Mon..Fri 10:15 Europe/Lisbon\nUnit=project-factory@dev.service\n");
  fs.writeFileSync(path.join(ud, "project-triage.timer"),
    "[Timer]\nOnCalendar=Mon..Fri 08:45 Europe/Lisbon\nUnit=project-factory@triage.service\n");

  const r = runDriver(world, "schedule", ["--adopt", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  const s = readConfig(world).schedule;
  assert.equal(s.kind, "systemd");
  assert.equal(s.timezone, "Europe/Lisbon");
  assert.deepEqual(s.modes.dev, { time: "10:15", days: "Mon-Fri" });
  assert.deepEqual(s.modes.triage, { time: "08:45", days: "Mon-Fri" });
  assert.equal(s.modes.report, undefined, "adopt declares exactly what is installed");
});

test("schedule --adopt fails when nothing is installed", (t) => {
  const world = makeFactory(t);
  const r = runDriver(world, "schedule", ["--adopt", "--yes"]);
  assert.equal(r.code, 1);
  assert.match(r.stderr, /nothing|no scheduler/i);
  assert.match(r.stderr, /--declare/);
});

test("a prefix-sibling project's artifacts are never claimed — adopt sees nothing to adopt", (t) => {
  // /a/project must not match /a/project2 (the melkaia-twins class): a raw
  // substring match would let --uninstall delete the sibling's units and
  // --adopt import the sibling's times.
  const world = makeFactory(t);
  const sibling = `${world.project}2`;
  const ud = unitDir(world);
  fs.mkdirSync(ud, { recursive: true });
  fs.writeFileSync(path.join(ud, "project2-factory@.service"),
    `[Service]\nWorkingDirectory=${sibling}\nEnvironment=PATH=/usr/bin:/bin\nExecStart=/usr/bin/node /r/factory.mjs %i --project ${sibling} --scheduled\n`);
  fs.writeFileSync(path.join(ud, "project2-dev.timer"),
    "[Timer]\nOnCalendar=Mon..Fri 09:00\nUnit=project2-factory@dev.service\n");
  const la = path.join(world.home, "Library", "LaunchAgents");
  fs.mkdirSync(la, { recursive: true });
  fs.writeFileSync(path.join(la, "com.factory.project2.dev.plist"),
    `<plist><dict><key>Label</key><string>com.factory.project2.dev</string><key>ProgramArguments</key><array><string>node</string><string>/r/factory.mjs</string><string>dev</string><string>--project</string><string>${sibling}</string></array><key>WorkingDirectory</key><string>${sibling}</string></dict></plist>`);

  const r = runDriver(world, "schedule", ["--adopt", "--yes"]);

  assert.equal(r.code, 1, `sibling artifacts were claimed:\n${r.stdout}\n${r.stderr}`);
  assert.match(r.stderr, /nothing|no scheduler/i);
});

test("schedule --uninstall leaves a prefix-sibling project's units alone", (t) => {
  const world = makeFactory(t, { config: { schedule: SYSTEMD_BLOCK } });
  stubSystemctl(world);
  assert.equal(runDriver(world, "schedule", ["--install", "--yes"]).code, 0);
  const sibling = `${world.project}2`;
  const ud = unitDir(world);
  fs.writeFileSync(path.join(ud, "project2-factory@.service"),
    `[Service]\nWorkingDirectory=${sibling}\nExecStart=/usr/bin/node /r/factory.mjs %i --project ${sibling} --scheduled\n`);
  fs.writeFileSync(path.join(ud, "project2-dev.timer"),
    "[Timer]\nOnCalendar=Mon..Fri 09:00\nUnit=project2-factory@dev.service\n");

  const r = runDriver(world, "schedule", ["--uninstall", "--yes"]);

  assert.equal(r.code, 0, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.equal(fs.existsSync(path.join(ud, "project-dev.timer")), false, "own units removed");
  assert.ok(fs.existsSync(path.join(ud, "project2-factory@.service")), "sibling service survives");
  assert.ok(fs.existsSync(path.join(ud, "project2-dev.timer")), "sibling timer survives");
});

test("schedule --adopt refuses an installed schedule that parses into an invalid declaration", (t) => {
  const world = makeFactory(t);
  const cronFile = stubCrontab(world);
  // cron's `5-1` wraps — it parses to an empty day set, which must be
  // refused loudly, never written as days: ""
  fs.writeFileSync(cronFile,
    `0 9 * * 5-1 /usr/bin/node /r/factory.mjs dev --project ${world.project} --scheduled\n`);

  const r = runDriver(world, "schedule", ["--adopt", "--yes"]);

  assert.equal(r.code, 1, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stderr, /days/i);
  assert.equal(readConfig(world).schedule, "manual", "config untouched");
});

test("schedule --install refuses a crontab whose managed END marker was hand-deleted", (t) => {
  const world = makeFactory(t, { config: { schedule: { ...SYSTEMD_BLOCK, kind: "cron" } } });
  const cronFile = stubCrontab(world);
  fs.writeFileSync(cronFile,
    `# BEGIN factory ${world.project} (managed by factory.mjs schedule — do not edit inside)\n` +
    "0 9 * * 1-5 stale-entry\n" +
    "5 5 * * * /usr/bin/backup\n"); // END marker gone — the backup line must not be eaten

  const r = runDriver(world, "schedule", ["--install", "--yes"]);

  assert.equal(r.code, 1, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stderr, /END/);
  assert.match(fs.readFileSync(cronFile, "utf8"), /backup/, "crontab untouched");
});

test("schedule --adopt fails when two scheduler kinds reference the project", (t) => {
  const world = makeFactory(t);
  const ud = unitDir(world);
  fs.mkdirSync(ud, { recursive: true });
  fs.writeFileSync(path.join(ud, "project-dev.timer"),
    `[Timer]\nOnCalendar=Mon..Fri 09:00\nUnit=project-factory@dev.service\n`);
  fs.writeFileSync(path.join(ud, "project-factory@.service"),
    `[Service]\nExecStart=/usr/bin/node /r/factory.mjs %i --project ${world.project} --scheduled\n`);
  const la = path.join(world.home, "Library", "LaunchAgents");
  fs.mkdirSync(la, { recursive: true });
  fs.writeFileSync(path.join(la, "com.factory.project.dev.plist"),
    `<plist><dict><key>Label</key><string>com.factory.project.dev</string><key>ProgramArguments</key><array><string>node</string><string>/r/factory.mjs</string><string>dev</string><string>--project</string><string>${world.project}</string></array><key>StartCalendarInterval</key><array><dict><key>Weekday</key><integer>1</integer><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict></array></dict></plist>`);

  const r = runDriver(world, "schedule", ["--adopt", "--yes"]);

  assert.equal(r.code, 1, `stdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
  assert.match(r.stderr, /systemd.*launchd|launchd.*systemd/);
});

// ---------- nextFire (PR-E: dashboard "next window") ----------
// 2026-07-08T10:00:00Z is a Wednesday. Declarations pin timezone to UTC so
// the tests hold on any machine; one case proves a non-UTC zone shifts the
// wall clock.

test("nextFire finds a fire later the same day", () => {
  const decl = { kind: "launchd", timezone: "UTC", modes: { dev: { time: "12:00", days: "Mon-Fri" } } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.mode, "dev");
  assert.equal(next.at, "2026-07-08T12:00:00.000Z");
  assert.equal(next.inMinutes, 120);
});

test("nextFire rolls past a time already gone today", () => {
  const decl = { kind: "systemd", timezone: "UTC", modes: { dev: { time: "09:00", days: "Mon-Fri" } } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.at, "2026-07-09T09:00:00.000Z", "Thursday, not today");
});

test("nextFire skips undeclared days to the next declared one", () => {
  const decl = { kind: "cron", timezone: "UTC", modes: { triage: { time: "09:00", days: "Mon" } } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.at, "2026-07-13T09:00:00.000Z", "next Monday");
});

test("nextFire returns the soonest fire across declared modes", () => {
  const decl = { kind: "systemd", timezone: "UTC", modes: {
    dev: { time: "12:00", days: "Mon-Fri" },
    triage: { time: "11:00", days: "Mon-Fri" },
  } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.mode, "triage");
  assert.equal(next.inMinutes, 60);
});

test("nextFire honors the declared timezone", () => {
  // July: Europe/Lisbon = UTC+1, so 12:00 Lisbon = 11:00Z — one hour away.
  const decl = { kind: "cron", timezone: "Europe/Lisbon", modes: { dev: { time: "12:00", days: "Mon-Sun" } } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.inMinutes, 60);
});

test("nextFire is null for manual, kind-only, and broken declarations", () => {
  assert.equal(nextFire(normalizeSchedule("manual"), new Date()), null);
  assert.equal(nextFire(normalizeSchedule("launchd"), new Date()), null, "legacy kind-only has no times");
  assert.equal(nextFire(null, new Date()), null);
  assert.equal(nextFire({ kind: "cron", timezone: "Not/AZone", modes: { dev: { time: "09:00", days: "Mon" } } }, new Date()), null, "bad timezone never throws");
  assert.equal(nextFire({ kind: "cron", modes: { dev: { time: "junk", days: "Mon" } } }, new Date()), null, "bad time is skipped");
});

test("nextFire treats a fire due this exact minute as now", () => {
  const decl = { kind: "systemd", timezone: "UTC", modes: { dev: { time: "10:00", days: "Wed" } } };
  const next = nextFire(decl, new Date("2026-07-08T10:00:00Z"));
  assert.equal(next.inMinutes, 0);
});
